import { STATUS_FLOW } from "../constants";

export const customTaskTitleStyle = {
	marginBottom: '20px',
	fontSize: '18px',
	fontFamily: 'CoHeadline'
};

export enum ACTIONS {
	REJECT_DEFINITIVE = 'REJECT_DEFINITIVE',
	APPROVE_DEFINITIVE = 'APPROVE_DEFINITIVE',
	RETURN = 'RETURN',
	REQUEST = 'REQUEST',
	SUBMIT_REVIEW = 'SUBMIT_REVIEW',
	APPROVE_DRAFT = 'APPROVE_DRAFT',
	RETURN_DRAFT = 'RETURN_DRAFT',
	SUBMIT_REVIEW_DRAFT = 'SUBMIT_REVIEW_DRAFT',
}

export enum ACTIONS_TO_STATUS {
	REJECT_DEFINITIVE = STATUS_FLOW.REJECTED_DEFINITIVE,
	APPROVE_DEFINITIVE = STATUS_FLOW.APPROVED_DEFINITIVE,
	RETURN = STATUS_FLOW.RETURNED,
	REQUEST = STATUS_FLOW.REQUESTED,
	SUBMIT_REVIEW = STATUS_FLOW.IN_REVIEW,
	APPROVE_DRAFT = STATUS_FLOW.APPROVED_DRAFT,
	RETURN_DRAFT = STATUS_FLOW.RETURNED_DRAFT,
	SUBMIT_REVIEW_DRAFT = STATUS_FLOW.IN_REVIEW_DRAFT,
}
